[2023-10-01 08:00:03,789] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2023-01-26T00:00:00+00:00 [queued]>
[2023-10-01 08:00:04,806] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2023-01-26T00:00:00+00:00 [queued]>
[2023-10-01 08:00:04,853] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 08:00:04,859] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 08:00:04,863] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 08:00:05,594] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_name> on 2023-01-26T00:00:00+00:00
[2023-10-01 08:00:05,798] {standard_task_runner.py:52} INFO - Started process 24030 to run task
[2023-10-01 08:00:06,123] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_seventh_dag_v7', 'get_name', '2023-01-26T00:00:00+00:00', '--job-id', '2422', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_seventh_dag.py', '--cfg-path', '/tmp/tmp0lsv3lak', '--error-file', '/tmp/tmp7yo3zawt']
[2023-10-01 08:00:06,291] {standard_task_runner.py:77} INFO - Job 2422: Subtask get_name
[2023-10-01 08:00:07,966] {logging_mixin.py:104} INFO - Running <TaskInstance: our_seventh_dag_v7.get_name 2023-01-26T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 08:00:10,107] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_seventh_dag_v7
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2023-01-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-26T00:00:00+00:00
[2023-10-01 08:00:10,606] {python.py:118} INFO - Done. Returned value was: None
[2023-10-01 08:00:11,336] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_seventh_dag_v7, task_id=get_name, execution_date=20230126T000000, start_date=20231001T080004, end_date=20231001T080011
[2023-10-01 08:00:14,519] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 08:00:14,789] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 24030
[2023-10-01 08:00:14,855] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 08:00:15,856] {process_utils.py:66} INFO - Process psutil.Process(pid=24030, status='terminated', exitcode=1, started='08:00:04') (24030) terminated with exit code 1
