[2023-10-01 06:16:18,227] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-16T00:00:00+00:00 [queued]>
[2023-10-01 06:16:18,881] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-16T00:00:00+00:00 [queued]>
[2023-10-01 06:16:18,902] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:18,913] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:16:18,925] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:16:19,521] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-11-16T00:00:00+00:00
[2023-10-01 06:16:19,767] {standard_task_runner.py:52} INFO - Started process 5523 to run task
[2023-10-01 06:16:20,056] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2021-11-16T00:00:00+00:00', '--job-id', '752', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmp8dmucvfn', '--error-file', '/tmp/tmpka7zqv70']
[2023-10-01 06:16:20,216] {standard_task_runner.py:77} INFO - Job 752: Subtask first_task
[2023-10-01 06:16:22,123] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2021-11-16T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:16:24,586] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-16T00:00:00+00:00
[2023-10-01 06:16:24,700] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:16:25,243] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:16:25,621] {bash.py:169} INFO - Output:
[2023-10-01 06:16:25,678] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:16:25,685] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:16:28,625] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20211116T000000, start_date=20231001T061618, end_date=20231001T061628
[2023-10-01 06:16:33,762] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:16:33,852] {taskinstance.py:1220} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:16:34,119] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5523
[2023-10-01 06:16:34,584] {process_utils.py:66} INFO - Process psutil.Process(pid=5523, status='terminated', exitcode=0, started='06:16:19') (5523) terminated with exit code 0
