[2023-10-01 07:37:24,496] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2021-08-31T00:00:00+00:00 [queued]>
[2023-10-01 07:37:25,989] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2021-08-31T00:00:00+00:00 [queued]>
[2023-10-01 07:37:25,990] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:37:25,992] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 07:37:25,993] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:37:26,160] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_name> on 2021-08-31T00:00:00+00:00
[2023-10-01 07:37:26,458] {standard_task_runner.py:52} INFO - Started process 18385 to run task
[2023-10-01 07:37:26,873] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_seventh_dag_v7', 'get_name', '2021-08-31T00:00:00+00:00', '--job-id', '1395', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_seventh_dag.py', '--cfg-path', '/tmp/tmpu3e4ewuk', '--error-file', '/tmp/tmpbeixgsa5']
[2023-10-01 07:37:27,017] {standard_task_runner.py:77} INFO - Job 1395: Subtask get_name
[2023-10-01 07:37:28,299] {logging_mixin.py:104} INFO - Running <TaskInstance: our_seventh_dag_v7.get_name 2021-08-31T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 07:37:28,909] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_seventh_dag_v7
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2021-08-31T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-31T00:00:00+00:00
[2023-10-01 07:37:29,486] {python.py:118} INFO - Done. Returned value was: None
[2023-10-01 07:37:29,822] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_seventh_dag_v7, task_id=get_name, execution_date=20210831T000000, start_date=20231001T073725, end_date=20231001T073729
[2023-10-01 07:37:32,262] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-01 07:37:32,668] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 07:37:32,797] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 18385
[2023-10-01 07:37:32,877] {process_utils.py:66} INFO - Process psutil.Process(pid=18385, status='terminated', exitcode=0, started='07:37:25') (18385) terminated with exit code 0
