[2023-10-01 06:24:33,744] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2022-02-03T00:00:00+00:00 [queued]>
[2023-10-01 06:24:35,470] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2022-02-03T00:00:00+00:00 [queued]>
[2023-10-01 06:24:35,512] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:24:35,520] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:24:35,735] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:24:36,246] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2022-02-03T00:00:00+00:00
[2023-10-01 06:24:36,591] {standard_task_runner.py:52} INFO - Started process 6839 to run task
[2023-10-01 06:24:36,846] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2022-02-03T00:00:00+00:00', '--job-id', '988', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpbgcwyx1_', '--error-file', '/tmp/tmp29kxiop6']
[2023-10-01 06:24:37,007] {standard_task_runner.py:77} INFO - Job 988: Subtask first_task
[2023-10-01 06:24:44,570] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2022-02-03T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:24:47,143] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-03T00:00:00+00:00
[2023-10-01 06:24:47,168] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:24:47,183] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:24:47,461] {bash.py:169} INFO - Output:
[2023-10-01 06:24:48,125] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:24:48,141] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:24:48,508] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20220203T000000, start_date=20231001T062433, end_date=20231001T062448
[2023-10-01 06:24:50,166] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:24:50,449] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6839
[2023-10-01 06:24:51,278] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:24:51,280] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:24:52,165] {process_utils.py:66} INFO - Process psutil.Process(pid=6839, status='terminated', exitcode=1, started='06:24:35') (6839) terminated with exit code 1
