[2023-10-01 07:56:59,036] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2022-12-25T00:00:00+00:00 [queued]>
[2023-10-01 07:57:00,072] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_seventh_dag_v7.get_name 2022-12-25T00:00:00+00:00 [queued]>
[2023-10-01 07:57:00,091] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:57:00,108] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 07:57:00,200] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 07:57:00,903] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_name> on 2022-12-25T00:00:00+00:00
[2023-10-01 07:57:01,048] {standard_task_runner.py:52} INFO - Started process 23465 to run task
[2023-10-01 07:57:01,246] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_seventh_dag_v7', 'get_name', '2022-12-25T00:00:00+00:00', '--job-id', '2357', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_seventh_dag.py', '--cfg-path', '/tmp/tmp51eyvojv', '--error-file', '/tmp/tmpwvh3ftyu']
[2023-10-01 07:57:01,444] {standard_task_runner.py:77} INFO - Job 2357: Subtask get_name
[2023-10-01 07:57:03,988] {logging_mixin.py:104} INFO - Running <TaskInstance: our_seventh_dag_v7.get_name 2022-12-25T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 07:57:05,211] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_seventh_dag_v7
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-25T00:00:00+00:00
[2023-10-01 07:57:05,908] {python.py:118} INFO - Done. Returned value was: None
[2023-10-01 07:57:06,103] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_seventh_dag_v7, task_id=get_name, execution_date=20221225T000000, start_date=20231001T075659, end_date=20231001T075706
[2023-10-01 07:57:06,666] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 07:57:06,678] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 23465
[2023-10-01 07:57:07,926] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 07:57:08,737] {process_utils.py:66} INFO - Process psutil.Process(pid=23465, status='terminated', exitcode=1, started='07:57:01') (23465) terminated with exit code 1
