[2023-10-01 06:02:22,282] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.first_task 2021-10-21T00:00:00+00:00 [queued]>
[2023-10-01 06:02:23,358] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.first_task 2021-10-21T00:00:00+00:00 [queued]>
[2023-10-01 06:02:23,368] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:02:23,372] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:02:23,384] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:02:24,238] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-10-21T00:00:00+00:00
[2023-10-01 06:02:24,351] {standard_task_runner.py:52} INFO - Started process 3424 to run task
[2023-10-01 06:02:24,390] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'first_task', '2021-10-21T00:00:00+00:00', '--job-id', '394', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmpy8qcnkdj', '--error-file', '/tmp/tmp7arfur6j']
[2023-10-01 06:02:24,400] {standard_task_runner.py:77} INFO - Job 394: Subtask first_task
[2023-10-01 06:02:26,149] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.first_task 2021-10-21T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:02:26,503] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-21T00:00:00+00:00
[2023-10-01 06:02:26,522] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:02:26,570] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:02:26,754] {bash.py:169} INFO - Output:
[2023-10-01 06:02:26,770] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:02:26,789] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:02:28,079] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=first_task, execution_date=20211021T000000, start_date=20231001T060222, end_date=20231001T060228
[2023-10-01 06:02:29,714] {taskinstance.py:1220} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:02:29,839] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:02:29,963] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3424
[2023-10-01 06:02:29,985] {process_utils.py:66} INFO - Process psutil.Process(pid=3424, status='terminated', exitcode=0, started='06:02:23') (3424) terminated with exit code 0
