[2023-10-01 06:15:26,051] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-04T00:00:00+00:00 [queued]>
[2023-10-01 06:15:26,408] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-11-04T00:00:00+00:00 [queued]>
[2023-10-01 06:15:26,409] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:15:26,420] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:15:26,424] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:15:26,597] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-11-04T00:00:00+00:00
[2023-10-01 06:15:26,709] {standard_task_runner.py:52} INFO - Started process 5353 to run task
[2023-10-01 06:15:26,814] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2021-11-04T00:00:00+00:00', '--job-id', '717', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmp539_n1x0', '--error-file', '/tmp/tmpba4b8jq0']
[2023-10-01 06:15:26,936] {standard_task_runner.py:77} INFO - Job 717: Subtask first_task
[2023-10-01 06:15:27,661] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2021-11-04T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:15:28,805] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-04T00:00:00+00:00
[2023-10-01 06:15:28,831] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:15:28,857] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:15:29,153] {bash.py:169} INFO - Output:
[2023-10-01 06:15:29,394] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:15:29,406] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:15:30,499] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20211104T000000, start_date=20231001T061526, end_date=20231001T061530
[2023-10-01 06:15:32,200] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:15:32,541] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
