[2023-10-01 05:56:35,879] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.first_task 2021-08-28T00:00:00+00:00 [queued]>
[2023-10-01 05:56:36,151] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.first_task 2021-08-28T00:00:00+00:00 [queued]>
[2023-10-01 05:56:36,152] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:56:36,156] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:56:36,158] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:56:36,499] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-08-28T00:00:00+00:00
[2023-10-01 05:56:36,638] {standard_task_runner.py:52} INFO - Started process 2645 to run task
[2023-10-01 05:56:36,840] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'first_task', '2021-08-28T00:00:00+00:00', '--job-id', '233', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmpxtzwcrjp', '--error-file', '/tmp/tmp05qtya3y']
[2023-10-01 05:56:36,924] {standard_task_runner.py:77} INFO - Job 233: Subtask first_task
[2023-10-01 05:56:38,671] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.first_task 2021-08-28T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:56:41,035] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-28T00:00:00+00:00
[2023-10-01 05:56:41,126] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:56:41,214] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 05:56:42,950] {bash.py:169} INFO - Output:
[2023-10-01 05:56:42,966] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 05:56:42,972] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:56:43,578] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=first_task, execution_date=20210828T000000, start_date=20231001T055635, end_date=20231001T055643
[2023-10-01 05:56:50,206] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 05:56:51,464] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 05:56:51,751] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2645
[2023-10-01 05:56:51,803] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 05:56:51,834] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 05:56:53,214] {process_utils.py:66} INFO - Process psutil.Process(pid=2645, status='terminated', exitcode=1, started='05:56:35') (2645) terminated with exit code 1
