[2023-10-01 05:33:14,435] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_second_dag_v2.first_task 2021-08-10T00:00:00+00:00 [queued]>
[2023-10-01 05:33:15,053] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_second_dag_v2.first_task 2021-08-10T00:00:00+00:00 [queued]>
[2023-10-01 05:33:15,068] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:33:15,084] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:33:15,100] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:33:15,884] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-08-10T00:00:00+00:00
[2023-10-01 05:33:16,249] {standard_task_runner.py:52} INFO - Started process 1133 to run task
[2023-10-01 05:33:16,429] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_second_dag_v2', 'first_task', '2021-08-10T00:00:00+00:00', '--job-id', '133', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_second_dag.py', '--cfg-path', '/tmp/tmps4nqbihw', '--error-file', '/tmp/tmpc3bd8zl9']
[2023-10-01 05:33:16,602] {standard_task_runner.py:77} INFO - Job 133: Subtask first_task
[2023-10-01 05:33:18,110] {logging_mixin.py:104} INFO - Running <TaskInstance: our_second_dag_v2.first_task 2021-08-10T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:33:19,057] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_second_dag_v2
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-10T00:00:00+00:00
[2023-10-01 05:33:19,088] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:33:19,148] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 05:33:20,026] {bash.py:169} INFO - Output:
[2023-10-01 05:33:20,168] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 05:33:20,212] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:33:21,144] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_second_dag_v2, task_id=first_task, execution_date=20210810T000000, start_date=20231001T053314, end_date=20231001T053321
[2023-10-01 05:33:23,054] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-01 05:33:23,061] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 05:33:23,095] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 1133
[2023-10-01 05:33:23,098] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 05:33:23,123] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 05:33:23,578] {process_utils.py:66} INFO - Process psutil.Process(pid=1133, status='terminated', exitcode=1, started='05:33:15') (1133) terminated with exit code 1
