[2023-10-01 06:25:20,158] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2022-02-08T00:00:00+00:00 [queued]>
[2023-10-01 06:25:23,893] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2022-02-08T00:00:00+00:00 [queued]>
[2023-10-01 06:25:23,917] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:25:24,013] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:25:24,015] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:25:24,509] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2022-02-08T00:00:00+00:00
[2023-10-01 06:25:24,584] {standard_task_runner.py:52} INFO - Started process 6940 to run task
[2023-10-01 06:25:24,927] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2022-02-08T00:00:00+00:00', '--job-id', '1005', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmp1q6ydhot', '--error-file', '/tmp/tmpww9a000a']
[2023-10-01 06:25:25,041] {standard_task_runner.py:77} INFO - Job 1005: Subtask first_task
[2023-10-01 06:25:29,400] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2022-02-08T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:25:31,915] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-08T00:00:00+00:00
[2023-10-01 06:25:31,925] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:25:32,004] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:25:32,563] {bash.py:169} INFO - Output:
[2023-10-01 06:25:32,571] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:25:32,582] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:25:36,425] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20220208T000000, start_date=20231001T062520, end_date=20231001T062536
[2023-10-01 06:25:37,482] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:25:37,617] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6940
[2023-10-01 06:25:37,685] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:25:37,687] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:25:38,047] {process_utils.py:66} INFO - Process psutil.Process(pid=6940, status='terminated', exitcode=1, started='06:25:23') (6940) terminated with exit code 1
