[2023-10-01 05:59:43,439] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.second_task 2021-09-18T00:00:00+00:00 [queued]>
[2023-10-01 05:59:43,686] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.second_task 2021-09-18T00:00:00+00:00 [queued]>
[2023-10-01 05:59:43,702] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:59:43,707] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:59:43,712] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:59:43,897] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-09-18T00:00:00+00:00
[2023-10-01 05:59:43,993] {standard_task_runner.py:52} INFO - Started process 3020 to run task
[2023-10-01 05:59:44,521] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'second_task', '2021-09-18T00:00:00+00:00', '--job-id', '306', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmp9ibx6ewh', '--error-file', '/tmp/tmpfe83bcyk']
[2023-10-01 05:59:44,809] {standard_task_runner.py:77} INFO - Job 306: Subtask second_task
[2023-10-01 05:59:45,840] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.second_task 2021-09-18T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:59:46,496] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-18T00:00:00+00:00
[2023-10-01 05:59:46,507] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:59:46,528] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 05:59:46,644] {bash.py:169} INFO - Output:
[2023-10-01 05:59:46,664] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 05:59:46,689] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:59:46,839] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=second_task, execution_date=20210918T000000, start_date=20231001T055943, end_date=20231001T055946
[2023-10-01 05:59:47,295] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 05:59:47,561] {local_task_job.py:146} INFO - Task exited with return code 0
