[2023-10-01 06:09:51,835] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-08-23T00:00:00+00:00 [queued]>
[2023-10-01 06:09:52,191] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.first_task 2021-08-23T00:00:00+00:00 [queued]>
[2023-10-01 06:09:52,194] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:09:52,201] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:09:52,203] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:09:52,453] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): first_task> on 2021-08-23T00:00:00+00:00
[2023-10-01 06:09:52,807] {standard_task_runner.py:52} INFO - Started process 4233 to run task
[2023-10-01 06:09:53,243] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'first_task', '2021-08-23T00:00:00+00:00', '--job-id', '496', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpj1a5xkqo', '--error-file', '/tmp/tmp627ibnm3']
[2023-10-01 06:09:53,383] {standard_task_runner.py:77} INFO - Job 496: Subtask first_task
[2023-10-01 06:09:55,250] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.first_task 2021-08-23T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:09:56,405] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-23T00:00:00+00:00
[2023-10-01 06:09:56,433] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:09:56,541] {bash.py:158} INFO - Running command: echo hello world, this is the first task!
[2023-10-01 06:09:56,954] {bash.py:169} INFO - Output:
[2023-10-01 06:09:57,032] {bash.py:173} INFO - hello world, this is the first task!
[2023-10-01 06:09:57,066] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:09:57,609] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=first_task, execution_date=20210823T000000, start_date=20231001T060951, end_date=20231001T060957
[2023-10-01 06:09:59,197] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:09:59,686] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 4233
[2023-10-01 06:10:00,099] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:10:00,103] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:10:00,616] {process_utils.py:66} INFO - Process psutil.Process(pid=4233, status='terminated', exitcode=1, started='06:09:52') (4233) terminated with exit code 1
